# ~/.config/foot/foot.ini

# Set your preferred font and size
font=UbuntuMono Nerd Font:size=14

pad=5x5

[cursor]
style=block
blink=yes

[colors-dark]
foreground=ffffff
background=000000
cursor=000000 ffffff

[csd]
# Disable foot's client-side window decoration title bars 
# and let Niri handle the clean window edges entirely
preferred=none
